[project]
name            = "aoc-utils"
version         = "0.1.0"
description     = "Advent of Code utilities"
requires-python = ">= 3.13"
dependencies    = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
